name: Deploy

on:
  push:
  schedule:
    - cron: '0 0 * * *'
jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Build And Deploy
    steps:
      - uses: actions/checkout@v2
      - name: Event Name
        run: |
          echo "$GITHUB_EVENT_NAME"
          echo "$GITHUB_EVENT_PATH"
      - name: Build Image
        id: build_image
        run: |
          docker build -t yaoa/chrome-vnc:build -f ./Dockerfile .
          export IMAGE_ID_TEMP=$(sudo docker images --filter=reference=yaoa/chrome-vnc:build --format "{{.ID}}")
          echo "##[set-output name=image_id;]$IMAGE_ID_TEMP"
      - name: Login
        env:
          dockerID: ${{ secrets.dockerID }}
          dockerPassword: ${{ secrets.dockerPassword }}
        run: |
          docker login -u $dockerID -p $dockerPassword
      - name: Deploy Commit ID
        if: ${{ github.head_ref == '' && github.sha != '' }}
        env:
          image_id: ${{ steps.build_image.outputs.image_id }}
        run: |
          docker tag $image_id yaoa/chrome-vnc:$GITHUB_SHA
          docker push yaoa/chrome-vnc:$GITHUB_SHA
      - name: Deploy Latest
        if: ${{ github.head_ref == '' && github.ref == 'refs/heads/master' }}
        env:
          image_id: ${{ steps.build_image.outputs.image_id }}
        run: |
          docker tag $image_id yaoa/chrome-vnc:latest
          docker push yaoa/chrome-vnc:latest
      - name: Deploy Develop
        if: ${{ github.head_ref == '' && startsWith(github.ref, 'refs/heads/dev') }}
        env:
          image_id: ${{ steps.build_image.outputs.image_id }}
        run: |
          docker tag $image_id yaoa/chrome-vnc:latest-develop
          docker push yaoa/chrome-vnc:latest-develop
      - name: Deploy Branch
        if: ${{ github.head_ref == '' && startsWith(github.ref, 'refs/heads/') }}
        env:
          image_id: ${{ steps.build_image.outputs.image_id }}
        run: |
          docker tag $image_id yaoa/chrome-vnc:${GITHUB_REF##*/}
          docker push yaoa/chrome-vnc:${GITHUB_REF##*/}
      - name: Deploy Tag
        if: ${{ github.head_ref == '' && startsWith(github.ref, 'refs/tags/') }}
        env:
          image_id: ${{ steps.build_image.outputs.image_id }}
        run: |
          docker tag $image_id yaoa/chrome-vnc:${GITHUB_REF##*/}
          docker push yaoa/chrome-vnc:${GITHUB_REF##*/}
